name: Gerar Cobrinha (Snake)

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gerar a Cobrinha Blue Steel
        uses: Platane/snk@v3
        with:
          github_user_name: josegabrieldev

          theme: |
            {
              "background": "#0C111A",
              "snake": "#00ADEF",

              "color_empty": "#0C111A",
              "color_level_0": "#101822",

              "color_level_1": "#1A2738",
              "color_level_2": "#223144",
              "color_level_3": "#2D3E54",
              "color_level_4": "#00ADEF"
            }

          outputs: |
            dist/github-snake.svg

      - name: Publicar na branch saida
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: saida
          folder: dist
          clean: true
