name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza todos os dias à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: josegabrieldev
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      - name: Publicar no branch Saída
        uses: crazy-max/ghaction-git@v3
        with:
          target_branch: Saída
          commit_message: "Atualizando animação da cobrinha"
          allow_empty_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
