name: Gerar Cobrinha (Snake)

on:
  schedule:
    - cron: "0 0 * * *"   # Gera todos os dias à meia-noite
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: josegabrieldev
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      - name: Publicar arquivos da cobrinha na branch Saída
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: Saída
          publish_dir: dist
